repositories:
  - name: nvdp
    url: https://nvidia.github.io/k8s-device-plugin

releases:
  - name: nvidia-device-plugin
    namespace: nvidia
    chart: nvdp/nvidia-device-plugin
    values:
      - nodeSelector:
          zeet.co/gpu: "true"
